# Dependabot configuration for Next.js project with pnpm workspaces
# Using latest Dependabot features and best practices for 2024/2025

version: 2

updates:
  # NPM ecosystem for JavaScript/TypeScript dependencies
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
      timezone: 'UTC'

    # Dependency groups to reduce PR noise
    groups:
      # Frontend dependencies group
      frontend:
        applies-to: version-updates
        patterns:
          - 'react*'
          - 'next*'
          - '@types/react*'
          - 'typescript'
          - 'eslint*'
          - 'prettier*'
        update-types:
          - 'minor'
          - 'patch'

      # UI/Styling dependencies group
      ui-styling:
        applies-to: version-updates
        patterns:
          - '@radix-ui/*'
          - 'tailwind*'
          - '@tailwindcss/*'
          - 'class-variance-authority'
          - 'clsx'
          - 'tailwind-merge'
          - 'lucide-react'
          - 'tw-animate-css'
        update-types:
          - 'minor'
          - 'patch'

      # Major updates group (separate PRs for careful review)
      major-updates:
        applies-to: version-updates
        patterns:
          - '*'
        update-types:
          - 'major'

    # Commit message customization
    commit-message:
      prefix: 'deps'
      prefix-development: 'deps-dev'
      include: 'scope'

    # PR customization
    labels:
      - 'dependencies'
      - 'javascript'

    # Conservative PR limits to reduce conflicts
    open-pull-requests-limit: 5

    # Cooldown period to avoid too frequent updates and conflicts
    cooldown:
      default-days: 14
      semver-major-days: 60
      semver-minor-days: 14
      semver-patch-days: 7

    # Versioning strategy for this project type
    versioning-strategy: 'increase-if-necessary'

    # Allow only direct dependencies to reduce conflicts
    allow:
      - dependency-type: 'direct'

    # Ignore certain updates that might be problematic
    ignore:
      # Ignore React pre-release versions (alpha, beta, rc, canary)
      - dependency-name: 'react'
        versions: ['>19.0.0-0']
      - dependency-name: 'react-dom'
        versions: ['>19.0.0-0']
      
      # Ignore beta/experimental packages that might cause resolution issues
      - dependency-name: 'tailwindcss'
        versions: ['>=4.0.0-alpha.0 <5.0.0']
      - dependency-name: '@tailwindcss/*'
        versions: ['>=4.0.0-alpha.0 <5.0.0']

      # Ignore major version updates for these critical packages
      # (they will be handled by the major-updates group)
      - dependency-name: 'next'
        update-types: ['version-update:semver-major']
      - dependency-name: 'typescript'
        update-types: ['version-update:semver-major']
      - dependency-name: 'eslint'
        update-types: ['version-update:semver-major']

  # GitHub Actions ecosystem
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '10:00'
      timezone: 'UTC'

    # Group GitHub Actions updates
    groups:
      github-actions:
        applies-to: version-updates
        patterns:
          - '*'
        update-types:
          - 'major'
          - 'minor'
          - 'patch'

    commit-message:
      prefix: 'ci'
      include: 'scope'

    labels:
      - 'github-actions'
      - 'ci'

    open-pull-requests-limit: 5
