[tools]
# Node.js version - using LTS version 22
node = "22.18.0"

# pnpm package manager
pnpm = "10.14.0"

[env]
# Ensure Node.js options for development
NODE_OPTIONS = "--max-old-space-size=4096"

# Set environment for development
NODE_ENV = "development"


[settings]
# Auto-install missing tools
auto_install = true

# Show mise status in shell prompt
status = { missing_tools = "if_other_versions_installed", show_env = false, show_tools = false }
